name: Linters
on: [push,pull_request]
jobs:
  java-linter:
    name: Google Java Style
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Reformat & Commit
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"